version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  openrefine:
    image: felixlohmeier/openrefine:latest
    ports:
      - "3333:3333"
    volumes:
      - ./data:/data

volumes:
  postgres_data:
